spring:
  redis:
    host: 127.0.0.1
    port: 6379
    redisson:
      config: "classpath:redisson.yaml"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transactionIdPrefix: g1_trnx
      client-id: ttt
    consumer:
      groupId: myGroup
  datasource:
    url: jdbc:mysql://192.168.99.100/test?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver