spring:
  redis:
    host: 127.0.0.1
    port: 6379
    redisson:
      config: "classpath:redisson.yaml"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transactionIdPrefix: g1_trnx
      client-id: ttt
    consumer:
      groupId: myGroup